# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b93252d9cbbac5c80fd995649a219c29ac923ae35e5eadc791b310f1603a4a148bd43c0b04e33227629dfe20c253f2b9e1c9f7238f748c3651bac4bb3322a1b2

test:
  secret_key_base: 2c97345055c4ceabd66c43fe22ee44b04c41f18c8c2bbfdfa3bbcd3b29d358e622598855c9c9a4dd471dcfd8ebe1b441a71df27fb5d0773c26e5f67cc98217a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
